### ISSUE TITLE
can't import anything from package

### ISSUE THREAD

**Issue by gdamjan** [minimind/dispatch-on-value-for-python#3]
importing from the package (its __init__.py) doesn't work.

I guess it misses an `from .dispatchonvalue import *`

**Comment by minimind** [comment]
OK, I've change it so all of these work:

import dispatchonvalue 
from dispatchonvalue import *

Is this working the way you want it to?

**Comment by gdamjan** [comment]
you need `from .dispatchonvalue import *` so that it doesn't try to import the package itself

**Comment by gdamjan** [comment]
or just put the whole code in __init__.py
